project:
  type: website

website:
  title: "Merkayla"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: NM2207.qmd
        text: NM2207
      

format:
  html:
    theme: morph
    css: styles.css
    toc: true

editor: visual

