project:
  type: website
  output-dir: merkaylawong.github.io/docs

website:
  title: "Merkayla"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: NM2207.qmd
        text: NM2207
      

format:
  html:
    theme: morph
    css: styles.css
    toc: true

editor: visual

