project:
  type: website
  output-dir: /docs

website:
  title: "Merkayla"
  navbar:
    left:
      - index.qmd
      - about.qmd
      - NM2207.qmd
      

format:
  html:
    theme: morph
    css: styles.css
    toc: true

editor: visual

