---
title: "Code along 9 and challenge 9"
author: "Merkayla Wong"
date: "2023-10-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## slide 8a
**Solutions:** 
```{r, eval=TRUE,echo=TRUE}
# Enter code here
library(tidyverse)
tidydata <- tribble(
~country, ~year, ~cases, ~population,
"Afghanistan", 1999, 745, 19987071,
"Afghanistan", 2000, 2666, 20595360,
"Brazil", 1999, 37737, 172006362,
"Brazil", 2000, 80488, 174504898,
"China", 1999, 212258, 1272915272,
"China", 2000, 213766, 1280428583)
tidydata
```

## slide 8b
**Solutions:** 
```{r, eval=TRUE,echo=TRUE}
# Enter code here
nontidydata <- tribble(
~country,~year,~rate,
"Afghanistan", 1999, "745/19987071",
"Afghanistan", 2000, "2666/20595360",
"Brazil", 1999, "37737/172006362",
"Brazil", 2000, "80488/174504898",
"China", 1999, "212258/1272915272",
"China", 2000, "213766/1280428583")
nontidydata
```

## slide 8b
**Solutions:** 
```{r, eval=TRUE,echo=TRUE}
# Enter code here
nontidydata <- tribble(
~country,~year,~rate,
"Afghanistan", 1999, "745/19987071",
"Afghanistan", 2000, "2666/20595360",
"Brazil", 1999, "37737/172006362",
"Brazil", 2000, "80488/174504898",
"China", 1999, "212258/1272915272",
"China", 2000, "213766/1280428583")
nontidydata
```

## slide 11a
**Solutions:** 
```{r, eval=TRUE,echo=TRUE}
# Enter code here
nontidydata
```

## slide 11b
**Solutions:** 
```{r, eval=TRUE,echo=TRUE}
# Enter code here
tidieddata <- nontidydata %>%
separate(rate, into = c("cases",
"population"),
sep = "/")
tidieddata
```

## slide 12
**Solutions:** 
```{r, eval=TRUE,echo=TRUE}
# Enter code here
newtidieddata <- tidieddata %>%
pivot_longer(
cols = cases:population,
names_to = "measurement",
values_to = "value"
)
newtidieddata
```

## slide 14a
**Solutions:** 
```{r, eval=TRUE,echo=TRUE}
# Enter code here
df <- tribble(
~id, ~bp1, ~bp2,
"A", 100, 120,
"B", 140, 115,
"C", 120, 125
)
df
```

## slide 14b
**Solutions:** 
```{r, eval=TRUE,echo=TRUE}
# Enter code here
df %>%
pivot_longer(
cols = bp1:bp2,
names_to = "measurement",
values_to = "value"
)
```

## slide 18a
**Solutions:** 
```{r, eval=TRUE,echo=TRUE}
# Enter code here
newtidieddata
```

## slide 18b
**Solutions:** 
```{r, eval=TRUE,echo=TRUE}
# Enter code here
newtidieddata %>%
pivot_wider(names_from="measurement",
values_from="value")
```

## slide 19a
**Solutions:** 
```{r, eval=TRUE,echo=TRUE}
# Enter code here
newtidieddata
df <- tribble(
~id, ~measurement, ~value,
"A", "bp1", 100,
"B", "bp1", 140,
"B", "bp2", 115,
"A", "bp2", 120,
"A", "bp3", 105
)
df
```

## slide 19b
**Solutions:** 
```{r, eval=TRUE,echo=TRUE}
# Enter code here
df %>%
pivot_wider(
names_from = measurement,
values_from = value
)
```

## challenge 9 question 1
**Solutions:** 
```{r, eval=TRUE,echo=TRUE}
# Enter code here
tidied_dataset <- billboard %>%
pivot_longer(
cols = starts_with("wk"),
names_to = "week",
values_to = "rank"
)
tidied_dataset
```

```{r, eval=TRUE,echo=TRUE}
# Enter code here
tidied_dataset <- billboard %>%
pivot_longer(
cols = starts_with("wk"),
names_to = "week",
values_to = "rank",
values_drop_na = TRUE
)
tidied_dataset
```

```{r, eval=TRUE,echo=TRUE}
# Enter code here
tidied_dataset <- billboard %>%
pivot_longer(
cols = starts_with("wk"),
names_to = "week",
values_to = "rank",
values_drop_na = TRUE
)
tidied_dataset
```

```{r, eval=TRUE,echo=TRUE}
# Enter code here
tidied_dataset <- billboard %>%
pivot_longer(
cols = starts_with("wk"),
names_to = "week",
values_to = "rank",
values_drop_na = TRUE
)%>%
mutate(week = parse_number(week))
tidied_dataset 
```

```{r, eval=TRUE,echo=TRUE}
# Enter code here
ggplot(tidied_dataset, aes(x = week, y = rank, group = track)) +
  geom_line() +
  labs(x = "Week", y = "Rank") +
  ggtitle("Billboard Chart Rank Over Time")
``` 
## challenge 9 question 2
**Solutions:**
```{r, eval=TRUE,echo=TRUE}
# Enter code here
newtidieddata <- cms_patient_experience %>%
  pivot_wider(names_from = "measure_cd", values_from = "prf_rate")
newtidieddata
``` 

```{r, eval=TRUE,echo=TRUE}
# Enter code here
newtidieddata <- cms_patient_experience %>%
  pivot_wider(names_from = "measure_cd", values_from = "prf_rate", id_cols = starts_with("org"))
newtidieddata
``` 
